server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${xg.datasource.driver-class-name}
      url: jdbc:mysql://${xg.datasource.host}:${xg.datasource.port}/${xg.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${xg.datasource.username}
      password: ${xg.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.zhengru.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    top:
      zhengru:
        mapper: debug
        service: info
        controller: info

xg:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: hziee
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: xgto
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  alioss:
    access-key-id: ${xg.alioss.access-key-id}
    access-key-secret: ${xg.alioss.access-key-secret}
    bucket-name: ${xg.alioss.bucket-name}
    endpoint: ${xg.alioss.endpoint}
  wechat:
    appid: ${xg.wechat.appid}
    secret: ${xg.wechat.secret}