xg:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: xg_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: xxx
    access-key-secret: xxx
    bucket-name: xxx
    endpoint: oss-cn-hangzhou.aliyuncs.com
